base_uri: https://w3id.org/jp-naaa/
site_title: 全国学力調査LOD
output_dir: public/
top_class: https://w3id.org/jp-naaa/Test
subtitle_property_perclass:
  https://w3id.org/jp-naaa/Section: http://schema.org/alternateName
  https://w3id.org/jp-naaa/LessonPlan: http://schema.org/alternateName
google_analytics: G-X3FB78EC00