base_uri: https://w3id.org/jp-naaa/
site_title: 全国学力調査LOD
admin_name: 教育データプラス研究会
copyright_year: 2026-
output_dir: public/
top_class: https://w3id.org/jp-naaa/Test
locale: ja
subtitle_property_perclass:
  https://w3id.org/jp-naaa/Section: http://schema.org/alternateName
  https://w3id.org/jp-naaa/LessonPlan: http://schema.org/alternateName
css_file: style.css
javascript_file:
  - https://cdn.jsdelivr.net/npm/ldfetch@1.2/dist/main.min.js
  - script.js
google_analytics: G-X3FB78EC00
